// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/oganes5796/instagram-clon/internal/service.UserService -o user_service_minimock.go -n UserServiceMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/oganes5796/instagram-clon/internal/domain"
)

// UserServiceMock implements mm_service.UserService
type UserServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcRegister          func(ctx context.Context, user *domain.UserInfo) (i1 int64, err error)
	funcRegisterOrigin    string
	inspectFuncRegister   func(ctx context.Context, user *domain.UserInfo)
	afterRegisterCounter  uint64
	beforeRegisterCounter uint64
	RegisterMock          mUserServiceMockRegister

	funcSignin          func(ctx context.Context, username string, password string) (up1 *domain.User, err error)
	funcSigninOrigin    string
	inspectFuncSignin   func(ctx context.Context, username string, password string)
	afterSigninCounter  uint64
	beforeSigninCounter uint64
	SigninMock          mUserServiceMockSignin
}

// NewUserServiceMock returns a mock for mm_service.UserService
func NewUserServiceMock(t minimock.Tester) *UserServiceMock {
	m := &UserServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.RegisterMock = mUserServiceMockRegister{mock: m}
	m.RegisterMock.callArgs = []*UserServiceMockRegisterParams{}

	m.SigninMock = mUserServiceMockSignin{mock: m}
	m.SigninMock.callArgs = []*UserServiceMockSigninParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mUserServiceMockRegister struct {
	optional           bool
	mock               *UserServiceMock
	defaultExpectation *UserServiceMockRegisterExpectation
	expectations       []*UserServiceMockRegisterExpectation

	callArgs []*UserServiceMockRegisterParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UserServiceMockRegisterExpectation specifies expectation struct of the UserService.Register
type UserServiceMockRegisterExpectation struct {
	mock               *UserServiceMock
	params             *UserServiceMockRegisterParams
	paramPtrs          *UserServiceMockRegisterParamPtrs
	expectationOrigins UserServiceMockRegisterExpectationOrigins
	results            *UserServiceMockRegisterResults
	returnOrigin       string
	Counter            uint64
}

// UserServiceMockRegisterParams contains parameters of the UserService.Register
type UserServiceMockRegisterParams struct {
	ctx  context.Context
	user *domain.UserInfo
}

// UserServiceMockRegisterParamPtrs contains pointers to parameters of the UserService.Register
type UserServiceMockRegisterParamPtrs struct {
	ctx  *context.Context
	user **domain.UserInfo
}

// UserServiceMockRegisterResults contains results of the UserService.Register
type UserServiceMockRegisterResults struct {
	i1  int64
	err error
}

// UserServiceMockRegisterOrigins contains origins of expectations of the UserService.Register
type UserServiceMockRegisterExpectationOrigins struct {
	origin     string
	originCtx  string
	originUser string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmRegister *mUserServiceMockRegister) Optional() *mUserServiceMockRegister {
	mmRegister.optional = true
	return mmRegister
}

// Expect sets up expected params for UserService.Register
func (mmRegister *mUserServiceMockRegister) Expect(ctx context.Context, user *domain.UserInfo) *mUserServiceMockRegister {
	if mmRegister.mock.funcRegister != nil {
		mmRegister.mock.t.Fatalf("UserServiceMock.Register mock is already set by Set")
	}

	if mmRegister.defaultExpectation == nil {
		mmRegister.defaultExpectation = &UserServiceMockRegisterExpectation{}
	}

	if mmRegister.defaultExpectation.paramPtrs != nil {
		mmRegister.mock.t.Fatalf("UserServiceMock.Register mock is already set by ExpectParams functions")
	}

	mmRegister.defaultExpectation.params = &UserServiceMockRegisterParams{ctx, user}
	mmRegister.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmRegister.expectations {
		if minimock.Equal(e.params, mmRegister.defaultExpectation.params) {
			mmRegister.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmRegister.defaultExpectation.params)
		}
	}

	return mmRegister
}

// ExpectCtxParam1 sets up expected param ctx for UserService.Register
func (mmRegister *mUserServiceMockRegister) ExpectCtxParam1(ctx context.Context) *mUserServiceMockRegister {
	if mmRegister.mock.funcRegister != nil {
		mmRegister.mock.t.Fatalf("UserServiceMock.Register mock is already set by Set")
	}

	if mmRegister.defaultExpectation == nil {
		mmRegister.defaultExpectation = &UserServiceMockRegisterExpectation{}
	}

	if mmRegister.defaultExpectation.params != nil {
		mmRegister.mock.t.Fatalf("UserServiceMock.Register mock is already set by Expect")
	}

	if mmRegister.defaultExpectation.paramPtrs == nil {
		mmRegister.defaultExpectation.paramPtrs = &UserServiceMockRegisterParamPtrs{}
	}
	mmRegister.defaultExpectation.paramPtrs.ctx = &ctx
	mmRegister.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmRegister
}

// ExpectUserParam2 sets up expected param user for UserService.Register
func (mmRegister *mUserServiceMockRegister) ExpectUserParam2(user *domain.UserInfo) *mUserServiceMockRegister {
	if mmRegister.mock.funcRegister != nil {
		mmRegister.mock.t.Fatalf("UserServiceMock.Register mock is already set by Set")
	}

	if mmRegister.defaultExpectation == nil {
		mmRegister.defaultExpectation = &UserServiceMockRegisterExpectation{}
	}

	if mmRegister.defaultExpectation.params != nil {
		mmRegister.mock.t.Fatalf("UserServiceMock.Register mock is already set by Expect")
	}

	if mmRegister.defaultExpectation.paramPtrs == nil {
		mmRegister.defaultExpectation.paramPtrs = &UserServiceMockRegisterParamPtrs{}
	}
	mmRegister.defaultExpectation.paramPtrs.user = &user
	mmRegister.defaultExpectation.expectationOrigins.originUser = minimock.CallerInfo(1)

	return mmRegister
}

// Inspect accepts an inspector function that has same arguments as the UserService.Register
func (mmRegister *mUserServiceMockRegister) Inspect(f func(ctx context.Context, user *domain.UserInfo)) *mUserServiceMockRegister {
	if mmRegister.mock.inspectFuncRegister != nil {
		mmRegister.mock.t.Fatalf("Inspect function is already set for UserServiceMock.Register")
	}

	mmRegister.mock.inspectFuncRegister = f

	return mmRegister
}

// Return sets up results that will be returned by UserService.Register
func (mmRegister *mUserServiceMockRegister) Return(i1 int64, err error) *UserServiceMock {
	if mmRegister.mock.funcRegister != nil {
		mmRegister.mock.t.Fatalf("UserServiceMock.Register mock is already set by Set")
	}

	if mmRegister.defaultExpectation == nil {
		mmRegister.defaultExpectation = &UserServiceMockRegisterExpectation{mock: mmRegister.mock}
	}
	mmRegister.defaultExpectation.results = &UserServiceMockRegisterResults{i1, err}
	mmRegister.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmRegister.mock
}

// Set uses given function f to mock the UserService.Register method
func (mmRegister *mUserServiceMockRegister) Set(f func(ctx context.Context, user *domain.UserInfo) (i1 int64, err error)) *UserServiceMock {
	if mmRegister.defaultExpectation != nil {
		mmRegister.mock.t.Fatalf("Default expectation is already set for the UserService.Register method")
	}

	if len(mmRegister.expectations) > 0 {
		mmRegister.mock.t.Fatalf("Some expectations are already set for the UserService.Register method")
	}

	mmRegister.mock.funcRegister = f
	mmRegister.mock.funcRegisterOrigin = minimock.CallerInfo(1)
	return mmRegister.mock
}

// When sets expectation for the UserService.Register which will trigger the result defined by the following
// Then helper
func (mmRegister *mUserServiceMockRegister) When(ctx context.Context, user *domain.UserInfo) *UserServiceMockRegisterExpectation {
	if mmRegister.mock.funcRegister != nil {
		mmRegister.mock.t.Fatalf("UserServiceMock.Register mock is already set by Set")
	}

	expectation := &UserServiceMockRegisterExpectation{
		mock:               mmRegister.mock,
		params:             &UserServiceMockRegisterParams{ctx, user},
		expectationOrigins: UserServiceMockRegisterExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmRegister.expectations = append(mmRegister.expectations, expectation)
	return expectation
}

// Then sets up UserService.Register return parameters for the expectation previously defined by the When method
func (e *UserServiceMockRegisterExpectation) Then(i1 int64, err error) *UserServiceMock {
	e.results = &UserServiceMockRegisterResults{i1, err}
	return e.mock
}

// Times sets number of times UserService.Register should be invoked
func (mmRegister *mUserServiceMockRegister) Times(n uint64) *mUserServiceMockRegister {
	if n == 0 {
		mmRegister.mock.t.Fatalf("Times of UserServiceMock.Register mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmRegister.expectedInvocations, n)
	mmRegister.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmRegister
}

func (mmRegister *mUserServiceMockRegister) invocationsDone() bool {
	if len(mmRegister.expectations) == 0 && mmRegister.defaultExpectation == nil && mmRegister.mock.funcRegister == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmRegister.mock.afterRegisterCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmRegister.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Register implements mm_service.UserService
func (mmRegister *UserServiceMock) Register(ctx context.Context, user *domain.UserInfo) (i1 int64, err error) {
	mm_atomic.AddUint64(&mmRegister.beforeRegisterCounter, 1)
	defer mm_atomic.AddUint64(&mmRegister.afterRegisterCounter, 1)

	mmRegister.t.Helper()

	if mmRegister.inspectFuncRegister != nil {
		mmRegister.inspectFuncRegister(ctx, user)
	}

	mm_params := UserServiceMockRegisterParams{ctx, user}

	// Record call args
	mmRegister.RegisterMock.mutex.Lock()
	mmRegister.RegisterMock.callArgs = append(mmRegister.RegisterMock.callArgs, &mm_params)
	mmRegister.RegisterMock.mutex.Unlock()

	for _, e := range mmRegister.RegisterMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.i1, e.results.err
		}
	}

	if mmRegister.RegisterMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmRegister.RegisterMock.defaultExpectation.Counter, 1)
		mm_want := mmRegister.RegisterMock.defaultExpectation.params
		mm_want_ptrs := mmRegister.RegisterMock.defaultExpectation.paramPtrs

		mm_got := UserServiceMockRegisterParams{ctx, user}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmRegister.t.Errorf("UserServiceMock.Register got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRegister.RegisterMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.user != nil && !minimock.Equal(*mm_want_ptrs.user, mm_got.user) {
				mmRegister.t.Errorf("UserServiceMock.Register got unexpected parameter user, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRegister.RegisterMock.defaultExpectation.expectationOrigins.originUser, *mm_want_ptrs.user, mm_got.user, minimock.Diff(*mm_want_ptrs.user, mm_got.user))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmRegister.t.Errorf("UserServiceMock.Register got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmRegister.RegisterMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmRegister.RegisterMock.defaultExpectation.results
		if mm_results == nil {
			mmRegister.t.Fatal("No results are set for the UserServiceMock.Register")
		}
		return (*mm_results).i1, (*mm_results).err
	}
	if mmRegister.funcRegister != nil {
		return mmRegister.funcRegister(ctx, user)
	}
	mmRegister.t.Fatalf("Unexpected call to UserServiceMock.Register. %v %v", ctx, user)
	return
}

// RegisterAfterCounter returns a count of finished UserServiceMock.Register invocations
func (mmRegister *UserServiceMock) RegisterAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRegister.afterRegisterCounter)
}

// RegisterBeforeCounter returns a count of UserServiceMock.Register invocations
func (mmRegister *UserServiceMock) RegisterBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRegister.beforeRegisterCounter)
}

// Calls returns a list of arguments used in each call to UserServiceMock.Register.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmRegister *mUserServiceMockRegister) Calls() []*UserServiceMockRegisterParams {
	mmRegister.mutex.RLock()

	argCopy := make([]*UserServiceMockRegisterParams, len(mmRegister.callArgs))
	copy(argCopy, mmRegister.callArgs)

	mmRegister.mutex.RUnlock()

	return argCopy
}

// MinimockRegisterDone returns true if the count of the Register invocations corresponds
// the number of defined expectations
func (m *UserServiceMock) MinimockRegisterDone() bool {
	if m.RegisterMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.RegisterMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.RegisterMock.invocationsDone()
}

// MinimockRegisterInspect logs each unmet expectation
func (m *UserServiceMock) MinimockRegisterInspect() {
	for _, e := range m.RegisterMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserServiceMock.Register at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterRegisterCounter := mm_atomic.LoadUint64(&m.afterRegisterCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.RegisterMock.defaultExpectation != nil && afterRegisterCounter < 1 {
		if m.RegisterMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UserServiceMock.Register at\n%s", m.RegisterMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UserServiceMock.Register at\n%s with params: %#v", m.RegisterMock.defaultExpectation.expectationOrigins.origin, *m.RegisterMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcRegister != nil && afterRegisterCounter < 1 {
		m.t.Errorf("Expected call to UserServiceMock.Register at\n%s", m.funcRegisterOrigin)
	}

	if !m.RegisterMock.invocationsDone() && afterRegisterCounter > 0 {
		m.t.Errorf("Expected %d calls to UserServiceMock.Register at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.RegisterMock.expectedInvocations), m.RegisterMock.expectedInvocationsOrigin, afterRegisterCounter)
	}
}

type mUserServiceMockSignin struct {
	optional           bool
	mock               *UserServiceMock
	defaultExpectation *UserServiceMockSigninExpectation
	expectations       []*UserServiceMockSigninExpectation

	callArgs []*UserServiceMockSigninParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UserServiceMockSigninExpectation specifies expectation struct of the UserService.Signin
type UserServiceMockSigninExpectation struct {
	mock               *UserServiceMock
	params             *UserServiceMockSigninParams
	paramPtrs          *UserServiceMockSigninParamPtrs
	expectationOrigins UserServiceMockSigninExpectationOrigins
	results            *UserServiceMockSigninResults
	returnOrigin       string
	Counter            uint64
}

// UserServiceMockSigninParams contains parameters of the UserService.Signin
type UserServiceMockSigninParams struct {
	ctx      context.Context
	username string
	password string
}

// UserServiceMockSigninParamPtrs contains pointers to parameters of the UserService.Signin
type UserServiceMockSigninParamPtrs struct {
	ctx      *context.Context
	username *string
	password *string
}

// UserServiceMockSigninResults contains results of the UserService.Signin
type UserServiceMockSigninResults struct {
	up1 *domain.User
	err error
}

// UserServiceMockSigninOrigins contains origins of expectations of the UserService.Signin
type UserServiceMockSigninExpectationOrigins struct {
	origin         string
	originCtx      string
	originUsername string
	originPassword string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSignin *mUserServiceMockSignin) Optional() *mUserServiceMockSignin {
	mmSignin.optional = true
	return mmSignin
}

// Expect sets up expected params for UserService.Signin
func (mmSignin *mUserServiceMockSignin) Expect(ctx context.Context, username string, password string) *mUserServiceMockSignin {
	if mmSignin.mock.funcSignin != nil {
		mmSignin.mock.t.Fatalf("UserServiceMock.Signin mock is already set by Set")
	}

	if mmSignin.defaultExpectation == nil {
		mmSignin.defaultExpectation = &UserServiceMockSigninExpectation{}
	}

	if mmSignin.defaultExpectation.paramPtrs != nil {
		mmSignin.mock.t.Fatalf("UserServiceMock.Signin mock is already set by ExpectParams functions")
	}

	mmSignin.defaultExpectation.params = &UserServiceMockSigninParams{ctx, username, password}
	mmSignin.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSignin.expectations {
		if minimock.Equal(e.params, mmSignin.defaultExpectation.params) {
			mmSignin.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSignin.defaultExpectation.params)
		}
	}

	return mmSignin
}

// ExpectCtxParam1 sets up expected param ctx for UserService.Signin
func (mmSignin *mUserServiceMockSignin) ExpectCtxParam1(ctx context.Context) *mUserServiceMockSignin {
	if mmSignin.mock.funcSignin != nil {
		mmSignin.mock.t.Fatalf("UserServiceMock.Signin mock is already set by Set")
	}

	if mmSignin.defaultExpectation == nil {
		mmSignin.defaultExpectation = &UserServiceMockSigninExpectation{}
	}

	if mmSignin.defaultExpectation.params != nil {
		mmSignin.mock.t.Fatalf("UserServiceMock.Signin mock is already set by Expect")
	}

	if mmSignin.defaultExpectation.paramPtrs == nil {
		mmSignin.defaultExpectation.paramPtrs = &UserServiceMockSigninParamPtrs{}
	}
	mmSignin.defaultExpectation.paramPtrs.ctx = &ctx
	mmSignin.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSignin
}

// ExpectUsernameParam2 sets up expected param username for UserService.Signin
func (mmSignin *mUserServiceMockSignin) ExpectUsernameParam2(username string) *mUserServiceMockSignin {
	if mmSignin.mock.funcSignin != nil {
		mmSignin.mock.t.Fatalf("UserServiceMock.Signin mock is already set by Set")
	}

	if mmSignin.defaultExpectation == nil {
		mmSignin.defaultExpectation = &UserServiceMockSigninExpectation{}
	}

	if mmSignin.defaultExpectation.params != nil {
		mmSignin.mock.t.Fatalf("UserServiceMock.Signin mock is already set by Expect")
	}

	if mmSignin.defaultExpectation.paramPtrs == nil {
		mmSignin.defaultExpectation.paramPtrs = &UserServiceMockSigninParamPtrs{}
	}
	mmSignin.defaultExpectation.paramPtrs.username = &username
	mmSignin.defaultExpectation.expectationOrigins.originUsername = minimock.CallerInfo(1)

	return mmSignin
}

// ExpectPasswordParam3 sets up expected param password for UserService.Signin
func (mmSignin *mUserServiceMockSignin) ExpectPasswordParam3(password string) *mUserServiceMockSignin {
	if mmSignin.mock.funcSignin != nil {
		mmSignin.mock.t.Fatalf("UserServiceMock.Signin mock is already set by Set")
	}

	if mmSignin.defaultExpectation == nil {
		mmSignin.defaultExpectation = &UserServiceMockSigninExpectation{}
	}

	if mmSignin.defaultExpectation.params != nil {
		mmSignin.mock.t.Fatalf("UserServiceMock.Signin mock is already set by Expect")
	}

	if mmSignin.defaultExpectation.paramPtrs == nil {
		mmSignin.defaultExpectation.paramPtrs = &UserServiceMockSigninParamPtrs{}
	}
	mmSignin.defaultExpectation.paramPtrs.password = &password
	mmSignin.defaultExpectation.expectationOrigins.originPassword = minimock.CallerInfo(1)

	return mmSignin
}

// Inspect accepts an inspector function that has same arguments as the UserService.Signin
func (mmSignin *mUserServiceMockSignin) Inspect(f func(ctx context.Context, username string, password string)) *mUserServiceMockSignin {
	if mmSignin.mock.inspectFuncSignin != nil {
		mmSignin.mock.t.Fatalf("Inspect function is already set for UserServiceMock.Signin")
	}

	mmSignin.mock.inspectFuncSignin = f

	return mmSignin
}

// Return sets up results that will be returned by UserService.Signin
func (mmSignin *mUserServiceMockSignin) Return(up1 *domain.User, err error) *UserServiceMock {
	if mmSignin.mock.funcSignin != nil {
		mmSignin.mock.t.Fatalf("UserServiceMock.Signin mock is already set by Set")
	}

	if mmSignin.defaultExpectation == nil {
		mmSignin.defaultExpectation = &UserServiceMockSigninExpectation{mock: mmSignin.mock}
	}
	mmSignin.defaultExpectation.results = &UserServiceMockSigninResults{up1, err}
	mmSignin.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSignin.mock
}

// Set uses given function f to mock the UserService.Signin method
func (mmSignin *mUserServiceMockSignin) Set(f func(ctx context.Context, username string, password string) (up1 *domain.User, err error)) *UserServiceMock {
	if mmSignin.defaultExpectation != nil {
		mmSignin.mock.t.Fatalf("Default expectation is already set for the UserService.Signin method")
	}

	if len(mmSignin.expectations) > 0 {
		mmSignin.mock.t.Fatalf("Some expectations are already set for the UserService.Signin method")
	}

	mmSignin.mock.funcSignin = f
	mmSignin.mock.funcSigninOrigin = minimock.CallerInfo(1)
	return mmSignin.mock
}

// When sets expectation for the UserService.Signin which will trigger the result defined by the following
// Then helper
func (mmSignin *mUserServiceMockSignin) When(ctx context.Context, username string, password string) *UserServiceMockSigninExpectation {
	if mmSignin.mock.funcSignin != nil {
		mmSignin.mock.t.Fatalf("UserServiceMock.Signin mock is already set by Set")
	}

	expectation := &UserServiceMockSigninExpectation{
		mock:               mmSignin.mock,
		params:             &UserServiceMockSigninParams{ctx, username, password},
		expectationOrigins: UserServiceMockSigninExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSignin.expectations = append(mmSignin.expectations, expectation)
	return expectation
}

// Then sets up UserService.Signin return parameters for the expectation previously defined by the When method
func (e *UserServiceMockSigninExpectation) Then(up1 *domain.User, err error) *UserServiceMock {
	e.results = &UserServiceMockSigninResults{up1, err}
	return e.mock
}

// Times sets number of times UserService.Signin should be invoked
func (mmSignin *mUserServiceMockSignin) Times(n uint64) *mUserServiceMockSignin {
	if n == 0 {
		mmSignin.mock.t.Fatalf("Times of UserServiceMock.Signin mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSignin.expectedInvocations, n)
	mmSignin.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSignin
}

func (mmSignin *mUserServiceMockSignin) invocationsDone() bool {
	if len(mmSignin.expectations) == 0 && mmSignin.defaultExpectation == nil && mmSignin.mock.funcSignin == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSignin.mock.afterSigninCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSignin.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Signin implements mm_service.UserService
func (mmSignin *UserServiceMock) Signin(ctx context.Context, username string, password string) (up1 *domain.User, err error) {
	mm_atomic.AddUint64(&mmSignin.beforeSigninCounter, 1)
	defer mm_atomic.AddUint64(&mmSignin.afterSigninCounter, 1)

	mmSignin.t.Helper()

	if mmSignin.inspectFuncSignin != nil {
		mmSignin.inspectFuncSignin(ctx, username, password)
	}

	mm_params := UserServiceMockSigninParams{ctx, username, password}

	// Record call args
	mmSignin.SigninMock.mutex.Lock()
	mmSignin.SigninMock.callArgs = append(mmSignin.SigninMock.callArgs, &mm_params)
	mmSignin.SigninMock.mutex.Unlock()

	for _, e := range mmSignin.SigninMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.up1, e.results.err
		}
	}

	if mmSignin.SigninMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSignin.SigninMock.defaultExpectation.Counter, 1)
		mm_want := mmSignin.SigninMock.defaultExpectation.params
		mm_want_ptrs := mmSignin.SigninMock.defaultExpectation.paramPtrs

		mm_got := UserServiceMockSigninParams{ctx, username, password}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSignin.t.Errorf("UserServiceMock.Signin got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSignin.SigninMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.username != nil && !minimock.Equal(*mm_want_ptrs.username, mm_got.username) {
				mmSignin.t.Errorf("UserServiceMock.Signin got unexpected parameter username, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSignin.SigninMock.defaultExpectation.expectationOrigins.originUsername, *mm_want_ptrs.username, mm_got.username, minimock.Diff(*mm_want_ptrs.username, mm_got.username))
			}

			if mm_want_ptrs.password != nil && !minimock.Equal(*mm_want_ptrs.password, mm_got.password) {
				mmSignin.t.Errorf("UserServiceMock.Signin got unexpected parameter password, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSignin.SigninMock.defaultExpectation.expectationOrigins.originPassword, *mm_want_ptrs.password, mm_got.password, minimock.Diff(*mm_want_ptrs.password, mm_got.password))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSignin.t.Errorf("UserServiceMock.Signin got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSignin.SigninMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSignin.SigninMock.defaultExpectation.results
		if mm_results == nil {
			mmSignin.t.Fatal("No results are set for the UserServiceMock.Signin")
		}
		return (*mm_results).up1, (*mm_results).err
	}
	if mmSignin.funcSignin != nil {
		return mmSignin.funcSignin(ctx, username, password)
	}
	mmSignin.t.Fatalf("Unexpected call to UserServiceMock.Signin. %v %v %v", ctx, username, password)
	return
}

// SigninAfterCounter returns a count of finished UserServiceMock.Signin invocations
func (mmSignin *UserServiceMock) SigninAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSignin.afterSigninCounter)
}

// SigninBeforeCounter returns a count of UserServiceMock.Signin invocations
func (mmSignin *UserServiceMock) SigninBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSignin.beforeSigninCounter)
}

// Calls returns a list of arguments used in each call to UserServiceMock.Signin.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSignin *mUserServiceMockSignin) Calls() []*UserServiceMockSigninParams {
	mmSignin.mutex.RLock()

	argCopy := make([]*UserServiceMockSigninParams, len(mmSignin.callArgs))
	copy(argCopy, mmSignin.callArgs)

	mmSignin.mutex.RUnlock()

	return argCopy
}

// MinimockSigninDone returns true if the count of the Signin invocations corresponds
// the number of defined expectations
func (m *UserServiceMock) MinimockSigninDone() bool {
	if m.SigninMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SigninMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SigninMock.invocationsDone()
}

// MinimockSigninInspect logs each unmet expectation
func (m *UserServiceMock) MinimockSigninInspect() {
	for _, e := range m.SigninMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserServiceMock.Signin at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSigninCounter := mm_atomic.LoadUint64(&m.afterSigninCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SigninMock.defaultExpectation != nil && afterSigninCounter < 1 {
		if m.SigninMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UserServiceMock.Signin at\n%s", m.SigninMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UserServiceMock.Signin at\n%s with params: %#v", m.SigninMock.defaultExpectation.expectationOrigins.origin, *m.SigninMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSignin != nil && afterSigninCounter < 1 {
		m.t.Errorf("Expected call to UserServiceMock.Signin at\n%s", m.funcSigninOrigin)
	}

	if !m.SigninMock.invocationsDone() && afterSigninCounter > 0 {
		m.t.Errorf("Expected %d calls to UserServiceMock.Signin at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SigninMock.expectedInvocations), m.SigninMock.expectedInvocationsOrigin, afterSigninCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *UserServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockRegisterInspect()

			m.MinimockSigninInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *UserServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *UserServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockRegisterDone() &&
		m.MinimockSigninDone()
}
